// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGarageDB;

#nullable disable

namespace MyGarageDB.Migrations
{
    [DbContext(typeof(mygarageContext))]
    [Migration("20220923160345_Init_7")]
    partial class Init_7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("MyGarageDB.Entitys.OvnerDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNamber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ovners");
                });

            modelBuilder.Entity("MyGarageDB.GarageDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Sity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("garage", (string)null);
                });

            modelBuilder.Entity("MyGarageDB.TransportDB", b =>
                {
                    b.Property<int>("IdTr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("brand");

                    b.Property<int>("FuelQuntity")
                        .HasColumnType("int")
                        .HasColumnName("fuelQuntity");

                    b.Property<string>("FuelType")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("fuelType");

                    b.Property<int?>("GarageId")
                        .HasColumnType("int");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int")
                        .HasColumnName("maxSpeed");

                    b.Property<string>("Namber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("namber");

                    b.Property<bool?>("OnRoad")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OvnerId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("IdTr")
                        .HasName("PRIMARY");

                    b.HasIndex("GarageId");

                    b.HasIndex("OvnerId");

                    b.HasIndex("TypeId");

                    b.ToTable("transport", (string)null);
                });

            modelBuilder.Entity("MyGarageDB.TypeDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TypeTrans")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("type", (string)null);
                });

            modelBuilder.Entity("MyGarageDB.TransportDB", b =>
                {
                    b.HasOne("MyGarageDB.GarageDB", "Garage")
                        .WithMany("Transports")
                        .HasForeignKey("GarageId");

                    b.HasOne("MyGarageDB.Entitys.OvnerDB", "Ovner")
                        .WithMany("Transports")
                        .HasForeignKey("OvnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyGarageDB.TypeDB", "Type")
                        .WithMany("Transports")
                        .HasForeignKey("TypeId");

                    b.Navigation("Garage");

                    b.Navigation("Ovner");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MyGarageDB.Entitys.OvnerDB", b =>
                {
                    b.Navigation("Transports");
                });

            modelBuilder.Entity("MyGarageDB.GarageDB", b =>
                {
                    b.Navigation("Transports");
                });

            modelBuilder.Entity("MyGarageDB.TypeDB", b =>
                {
                    b.Navigation("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
